services:

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stats"]
      interval: 5s
      retries: 5

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm-main
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main -d ewm-main"]
      interval: 5s
      retries: 5

