spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main_service_admin_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**
          filters:
            - CircuitBreaker=myCircuitBreaker

        - id: main_service_category_route
          uri: lb://main-service
          predicates:
            - Path=/categories/**
          filters:
            - CircuitBreaker=myCircuitBreaker

        - id: main_service_events_route
          uri: lb://main-service
          predicates:
            - Path=/events/**
          filters:
            - CircuitBreaker=myCircuitBreaker

        - id: main_service_comments_route
          uri: lb://main-service
          predicates:
            - Path=/comments/**
          filters:
            - CircuitBreaker=myCircuitBreaker

        - id: main_service_compilations_route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
          filters:
            - CircuitBreaker=myCircuitBreaker

        - id: main_service_users_route
          uri: lb://main-service
          predicates:
            - Path=/users/**
          filters:
            - CircuitBreaker=myCircuitBreaker

server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true